include $(srctree)/drivers/misc/mediatek/Makefile.custom

obj-y   +=  mt65xx_lcm_list.o

ifeq ($(CONFIG_CUSTOM_KERNEL_LCM),"hx8394d_hd720_dsi_vdo_p34")
obj-y   +=  hx8394d_hd720_dsi_vdo_p34.o
endif

